[package]
name = "lkv"
version = "0.1.0"
edition = "2024"
rust-version = "1.90"
autobenches = false
description = "A lightweight and fast embedded key-value store for Rust."
readme = "../README.md"
license = "../LICENSE"
documentation = "https://docs.rs/lkv"
repository = "https://github.com/nuskey8/lkv"

[features]
ffi = []
nightly = []

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
crc32c = "0.6.8"
fs2 = "0.4.3"
memmap2 = "0.9.11"
rustc-hash = "=2.1.3"
xxhash-rust = { version = "=0.8.18", features = ["xxh3"] }

[dev-dependencies]
fjall = "3.1.8"
heed = "0.22.1"
jammdb = "0.11.0"
libc = "0.2.177"
redb = "4.1.0"
rocksdb = { version = "0.24.0", default-features = false, features = ["lz4", "bindgen-runtime"] }
rusqlite = { version = "0.38.0", features = ["bundled"] }
sled = "0.34.7"
tempfile = "3.5.0"

[[bench]]
name = "comparison"
harness = true
required-features = ["nightly"]

[[bench]]
name = "large_values"
harness = true
required-features = ["nightly"]

[[bench]]
name = "reopen"
harness = true
required-features = ["nightly"]

[[bench]]
name = "c_api"
harness = true
required-features = ["ffi", "nightly"]
