[package]
name = "lkv-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
lkv = { path = "../lkv" }

[[bin]]
name = "open_bytes"
path = "fuzz_targets/open_bytes.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
